name: Deploy

on:
  workflow_run:
    workflows: ["Formatting"]
    types:
      - completed

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Copy repository to vps
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.KEYSSH }}
      with:
        source: "."
        target: "/home/${{ secrets.USERNAME }}/aurora"